version: '3'
services:
  web:
    build:
      # where the files should come from
      context: .
      # location of Dockerfile
      dockerfile: Dockerfile.dev
    ports:
     - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
      - FAST_REFRESH=false
  web-tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]